version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - easypark-network

  # Client service
  client:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - easypark-network

  # Redis service
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - easypark-network

networks:
  easypark-network:
    name: easypark-network