version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"

  # Client service
  client:
    build:
      context: ./frontend
    ports:
      - "80:80"

networks:
  default:
    name: easypark-network