name: Deploy Web App - Frontend

on:
  push:
    branches:
      - main  # Use the branch you use for production

jobs:
  host-1:
    runs-on: money-tracker-deploy  
    steps:
      - uses: actions/checkout@v3
      
      # Setup Node.js with version 20
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      # Install dependencies
      - name: Install Dependencies
        run: npm install vite react react-dom
      
      # Build the React app
      - name: Build React App
        run: npm run build

      # Set up SSH key from GitHub Secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST1 }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST1 }}

      # Deploy to remote host via SSH
      - name: Deploy to Remote Server
        run: |
          rsync -av --exclude '.env' -e "ssh -p 22" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST1 }}:/var/www/html/ --rsync-path="sudo rsync"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST1 }} 'sudo systemctl restart nginx'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST1 }}
  host-2:
    runs-on: self-hosted  
    steps:
      - uses: actions/checkout@v3
      
      # Setup Node.js with version 20
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      # Install dependencies
      - name: Install Dependencies
        run: npm install
      
      # Build the React app
      - name: Build React App
        run: npm run build

      # Set up SSH key from GitHub Secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST2 }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST2 }}

      # Deploy to remote host via SSH
      - name: Deploy to Remote Server
        run: |
          rsync -av --exclude '.env' -e "ssh -p 22" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST1 }}:/var/www/html/ --rsync-path="sudo rsync"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST2 }} 'sudo systemctl restart nginx'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST2 }}

  